server:
  port: 8765

jwt:
  jwtSecret: "maybeitsmica"

eureka:
  client:
    enabled: true
    service-url:
      default-zone: "http://localhost:8761/eureka"

#spring:
#  cloud:
 #   gateway:
  #    globalcors:
   #     cors-configurations:
    #      '[/**]':
     #       allowedOrigins: "http://localhost:8080"
      #      allowedMethods: "*"